# Usage: make -f makefile.test

COMPILER = g++
OBJ_DIR = obj-test

OPTFLAGS = -O3 -march=native
CXXFLAGS = -std=c++20 $(OPTFLAGS) -I baseline-ogdf/OGDF/include -I baseline-ogdf/OGDF-build/include
LDFLAGS = -L baseline-ogdf/OGDF-build -lOGDF -lCOIN

# Source files
SRCS =  src/stats.cpp \
		src/sat/glucose.cpp \
		src/sat/cnf_builder.cpp \
		src/orthogonal/shape.cpp \
		src/orthogonal/shape_builder.cpp \
		src/drawing/polygon.cpp \
		src/drawing/svg_drawer.cpp \
		src/orthogonal/drawing_builder.cpp \
        baseline-ogdf/drawer.cpp

# Object files
OBJS = $(SRCS:%.cpp=$(OBJ_DIR)/%.o)

# Final output binary
TARGET = stats

# Build target
all: $(TARGET)

# Link object files into final binary
$(TARGET): $(OBJS)
	$(COMPILER) $(CXXFLAGS) $(OBJS) -o $(TARGET) $(LDFLAGS)

# Compile each source file into object file
$(OBJ_DIR)/%.o: %.cpp
	@mkdir -p $(dir $@)
	$(COMPILER) $(CXXFLAGS) -c $< -o $@

# Clean build files
clean:
	rm -rf $(OBJ_DIR) $(TARGET)
